homeassistant:
  name: Hjemme
  latitude: !secret zone_home_lat
  longitude: !secret zone_home_long
  elevation: 158
  unit_system: metric
  time_zone: Europe/Oslo

# BASIC MODULES
config:
logger:
  default: info
frontend:
mobile_app:
hassio:
updater:
history:
logbook:
map:
sun:
system_health:
cloud:
stream: #for camera record etc - maybe remove
# CUSTOM MODULES
nissan_leaf: !include leaf.yaml
asuswrt: !include asuswrt.yaml
tellduslive:
google:
  client_id: !secret googlekey
  client_secret: !secret googlesecret

# INCLUDES
camera: !include cameras.yaml
zone: !include zones.yaml
group: !include groups.yaml
light: !include lights.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

#customize: !include customize.yaml

sensor: !include_dir_merge_list sensors/ 
alert: !include_dir_merge_list alerts
binary_sensor: !include_dir_merge_list binary_sensors/
automation: !include_dir_merge_list automations/

#automation: !include automations.yaml
#alert: !include alerts.yaml
#binary_sensor: !include binary_sensors.yaml
#sensor: !include sensors.yaml