homeassistant:
  name: Hjemme
  latitude: !secret zone_home_lat
  longitude: !secret zone_home_long
  elevation: 158
  unit_system: metric
  time_zone: Europe/Oslo

# BASIC MODULES
config:
logger:
  default: info
frontend:
  themes: !include_dir_merge_named themes
mobile_app:
hassio:
updater:
history:
logbook:
map:
sun:
system_health:
cloud:
stream: #for camera record etc - maybe remove

# CUSTOM MODULES
asuswrt: !include asuswrt.yaml
tellduslive:
google:
  client_id: !secret googlekey
  client_secret: !secret googlesecret

# INCLUDES
camera: !include cameras.yaml
zone: !include zones.yaml
group: !include groups.yaml
scene: !include scenes.yaml
alert: !include alerts.yaml
light: !include lights.yaml
input_boolean: !include input_boolean.yaml

sensor: !include_dir_merge_list sensors/
binary_sensor: !include_dir_merge_list binary_sensors/
automation: !include_dir_merge_list automations/
script: !include_dir_merge_list script/
