# TIME
- platform: time_date
  display_options:
    - time

# Qbittorrent monitor
#- platform: qbittorrent
#  url: http://box.rotnes.org:9090
#  username: !secret qbittorrent_user
#  password: !secret qbittorrent_pw

# Steam
- platform: steam_online
  api_key: 20D2F496FF3FA95213C7D57A68CB9478
  accounts:
    - 76561197970426242
    - 76561198799039909
